SysHotel/Controllers/ClientController.cs
using DataClass.Entity.Interface;
using DataClass.Models.ViewModel;
using HotelSystem.Models.Main;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SysHotel.Data;

namespace SysHotel.Controllers
{
    public class ClientController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IClientService _clientService;
        public ClientController(ApplicationDbContext db,
        IClientService clientService)
        {
            _db = db;// bu asosiy Connect hamma Controllerda bo'ladi
            _clientService = clientService;
        }

        public IActionResult Index()
        {            
            var list =_clientService.GetClient();
            return View(list);
        }
        [HttpGet]
        public IActionResult Edit(int? Id)
        {         
            var ClientList =_db.Clients.ToList().FirstOrDefault(m => m.Id ==Id);
            if (ClientList == null)
            {
                return NotFound();
            }
            return View(ClientList);
        }
      
        public IActionResult Edit(Client model)
        {
            var entity = _db.Clients.FirstOrDefault(m => m.Id == model.Id);
            Client client = new Client();
            if (entity == null)
                return View("No content");
            entity.FirstName = client.FirstName;
            entity.LastName = client.LastName;
            entity.MiddleName = client.MiddleName;
            entity.Date_of_birth = client.Date_of_birth;
            entity.Passport_number = client.Passport_number;
            entity.Passport_series = client.Passport_series;
            _db.Clients.Update(entity);
            _db.SaveChanges();
            return View(entity);           

        }

        [HttpPost]
        public IActionResult Index(string ClientSearch)
        {
            ViewData["GetClientDetails"] = ClientSearch;
            var Clientquery = from x in _db.Clients select x;
            if (!String.IsNullOrEmpty(ClientSearch))
            {
                Clientquery = Clientquery.Where(x => x.FirstName.Contains(ClientSearch) || x.LastName.Contains(ClientSearch)||x.MiddleName.Contains(ClientSearch));
            }
            return View(Clientquery.ToList());
        }
    }
}

SysHotel/Controllers/OrderController.cs
        using DataClass.Entity.Interface;
using DataClass.Models;
using DataClass.Models.NewModels;
using DataClass.Models.ViewModel;
using HotelSystem.Models;
using HotelSystem.Models.Main;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SysHotel.Data;
using System.Security.Claims;

namespace SysHotel.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IUserService _userService;
        private readonly IClientService _clientService;
        private readonly IOrderService _orderService;
        private readonly IDistrictService _districtService;
        private readonly IPaymentService _paymentService;
        public OrderController(IClientService clientService,
             IUserService userService,
            IOrderService orderService,
            IDistrictService districtService,
            IPaymentService paymentService,
            ApplicationDbContext db)
        {
            _db = db;
            _userService = userService;
            _clientService = clientService;
            _orderService = orderService;
            _districtService = districtService;
            _paymentService = paymentService;
        }
        const string UserId = "_id";
        const string UserName = "_name";
        public IActionResult Index()
        {
            ConnectOrderToRoom returnModel=new ConnectOrderToRoom();
            var model = _orderService.GetOrdersViewList().OrderBy(x=>x.RoomId);
            List<AllViewModel> allView = new List<AllViewModel>();

            var roomList = _db.Rooms.ToList();
            foreach (var item in roomList)
            {
                var count = model.Where(m => m.Status == 1 && m.RoomId == item.Id).ToList();
                AllViewModel entity = new AllViewModel();
                entity.Id = item.Id;
                entity.RoomName = item.Name + " (" + item.Floor + "-floor)";
                if (count.Where(m => m.Brom == true).Count() > 0)
                {
                    entity.ActiveRoomCount = _db.RoomCapasitys.Find(item.RoomCapasityId).Count;
                }
                else
                {
                    entity.ActiveRoomCount = model.Where(m => m.Status == 1 && m.RoomId == item.Id).Count();
                }
                entity.RoomCount = _db.RoomCapasitys.Find(item.RoomCapasityId).Count - entity.ActiveRoomCount;
                var comment = model.Where(m => m.Status == 1 && m.RoomId == item.Id && m.Comment != null).FirstOrDefault();
                entity.Comment = comment == null ? "" : comment.Comment;
                allView.Add(entity);
            }
            returnModel.OrdersViewModels = model;
            returnModel.AllViewModels = allView;
            return View(returnModel);
        }
        public IActionResult EditOrder(int OrderId)
        {
            var order = _db.Orders.Find(OrderId);
            if (order != null)
            {
                var payclient = _db.PaymentClients.Find(order.PaymentClientId);

                EditOrderViewModel model = new EditOrderViewModel();
                model.Id = order.Id;
                var RoomList = _db.Rooms.Select(x => new
                {
                    Id = x.Id,
                    Name = x.Name
                }).ToList();
                ViewBag.RoomList = RoomList;
                var Client = _db.Clients.Find(payclient?.ClientId);
                model.FIO = Client?.FirstName + " " + Client?.LastName + " " + Client?.MiddleName;
                model.ClientID = Client.Id;
                model.PaymentForDay = order.DayPayment;
                model.AllBusy = order.Brom;
                model.Comment = order.Comment;
                model.RoomID = order.RoomId;
                return View(model);
            }
            return View();
        }
        [HttpPost]
        public IActionResult EditOrder(EditOrderViewModel model)
        {
            _orderService.UpdateOrders(model);
            return RedirectToAction("Index");
        }
        public IActionResult AddPay(int OrderId)
        {
            AddPayViewModel model=new AddPayViewModel();
            var order = _db.Orders.Find(OrderId);
            var payclient = _db.PaymentClients.Find(order.PaymentClientId);
            var PaymentTypeList = _db.Payment_types.Select(x => new
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();
            ViewBag.PaymentTypeList = PaymentTypeList;
            var Client = _db.Clients.Find(payclient?.ClientId);
            model.FIO = Client?.FirstName + " " + Client?.LastName + " " + Client?.MiddleName;
            model.ClientId = Client.Id;
            return View(model);
        }
        [HttpPost]
        public IActionResult AddPay(AddPayViewModel model)
        {
            if (model==null)
            {
                return null;
            }
            model.UsertId = (int)HttpContext.Session.GetInt32(UserId);
            _paymentService.AddPay(model);
            return RedirectToAction("Index");
        }
        public IActionResult CreateClient(int error=0)
        {
            var Genderlist = _db.Genders.Select(x => new
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();
            ViewBag.Genderlist = Genderlist;
            if (error>0)
            {
                ViewBag.Message = "This person already exists";
            }
            return View();
        }
        [HttpPost]
        public IActionResult CreateClient(Client model)
        {
            if (model!=null)
            {
                model.DistrictId = 1;
                var FindClient=_db.Clients.Where(m=>m.Passport_series==model.Passport_series&&
                                                    m.Passport_number == model.Passport_number).FirstOrDefault();
                if (FindClient == null)
                {
                    _clientService.Add(model);
                    return RedirectToAction("CreateOrder", new { ClientId = model.Id });
                }
            }
            return RedirectToAction("CreateClient", new {error=1});
        }
        public IActionResult CreateOrder(int OrderId=0,int ClientId=0)
        {
            AddNewOrderViewModel model = new AddNewOrderViewModel();
            var PaymentTypeList = _db.Payment_types.Select(x => new
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();
            var RoomList = _db.Rooms.Select(x => new
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();
            ViewBag.RoomList = RoomList;
            ViewBag.PaymentTypeList = PaymentTypeList;
            model.FIO = "No client found";
            model.ClientID = 0;
            if (ClientId>0)
            {
                var Client = _db.Clients.Find(ClientId);
                model.FIO = Client.FirstName + " " + Client.LastName + " " + Client.MiddleName;
                model.ClientID = Client.Id;
            }

            if (OrderId >0)
            {
                var Order =_orderService.Get(OrderId);
                if (Order != null)
                {
                    var payClient=_db.PaymentClients.Find(Order.Id);
                    var pay=_db.Payments.Find(payClient.PaymentId);
                    var Client = _db.Clients.Find(payClient.ClientId);
                    model.Id = Order.Id;
                    model.ClientID = Client.Id;
                    model.FIO= Client.FirstName + " " + Client.LastName + " " + Client.MiddleName;
                    model.Payment_type = pay.Payment_typeId;
                    model.RoomName = Order.RoomId;
                    model.Payment = pay.PaymentValue;
                    model.PaymentForDay = Order.DayPayment;
                    model.Comment = Order.Comment;
                    model.AllBusy = Order.Brom;
                }
            }

            return View(model);
        }
        [HttpPost]
        public IActionResult CreateOrder(AddNewOrderViewModel model)
        {
            try
            {
                model.UserID = (int)HttpContext.Session.GetInt32(UserId);
                _orderService.AddOrders(model);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                throw;
            }
        }
        public IActionResult CheckOut(int OrderID)
        {
            var order=_orderService.Get(OrderID);
            order.OrderStatus_typeId = 2;
            order.CheckOutTime = DateTime.Now;
            _orderService.Update(order);
            return RedirectToAction("Index");
        }

        public IActionResult SearchClient(ClientFilterModel model)
        {
            int ClId=_clientService.SearchClient(model);
            return RedirectToAction("CreateOrder",new { ClientId = ClId});
        }
    }
}

SysHotel/Controllers/PaymentController.cs
using DataClass.Entity.Interface;
using DataClass.Models;
using DataClass.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SysHotel.Data;

namespace SysHotel.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IClientService _clientService;

        public PaymentController(ApplicationDbContext db,
        IClientService clientService)
        {
            _db= db;
            _clientService= clientService;
        }
        public IActionResult Index(int ClientId=0)
        {
            List<PaymentViewModel> model=new List<PaymentViewModel>();
            if (ClientId!=0)
            {
                var paymentOrder = _db.PaymentClients.Where(m => m.ClientId == ClientId).ToList();
                foreach (var item in paymentOrder)
                {
                    var payment = _db.Payments.Find(item.PaymentId);
                    if (payment != null)
                    {
                        PaymentViewModel entity = new PaymentViewModel();
                        entity.Id = payment.Id;
                        entity.Payment = payment.PaymentValue.ToString();
                        entity.PaymentTypeName = _db.Payment_types.Find(payment.Payment_typeId).Name;
                        entity.PaymentTime = payment.PaymentTime;
                        model.Add(entity);
                    }
                }
            }
            else
            {
                var PaymentList = _db.Payments.Where(m => m.PaymentTime.Day == DateTime.Now.Day);
                foreach (var item in PaymentList)
                {
                    PaymentViewModel entity = new PaymentViewModel();
                    entity.Id = item.Id;
                    entity.Payment = item.PaymentValue.ToString();
                    entity.PaymentTypeName = _db.Payment_types.Find(item.Payment_typeId).Name;
                    entity.PaymentTime=item.PaymentTime;
                    model.Add(entity);
                }
                ViewBag.Error = "No client found";
            }
            return View(model);
        }
        public IActionResult SearchClient(ClientFilterModel model)
           {
            int ClId = _clientService.SearchClient(model);
            return RedirectToAction("Index", new { ClientId = ClId });
        }

       


    }
}

SysHotel/Controllers/ReportController.cs
using DataClass.Entity.Interface;
using DataClass.Models;
using DataClass.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SysHotel.Data;



namespace SysHotel.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IPaymentService _paymentService;

        public ReportController(ApplicationDbContext db,
            IPaymentService paymentService
            )
        {
            _db = db;
            _paymentService = paymentService;
        }
        public IActionResult Index()
        {
            var returnModel=_paymentService.DayReport();
            return View(returnModel);
        }
    }
}

SysHotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SysHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SysHotel.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SysHotel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Index">Payment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Client</a>
                        </li>
                        <li class="nav-item" >
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Reference" asp-action="IndexRegion">Reference</a>*@
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Reference</a>
                            <ul class="dropdown-menu" style="margin-left: 380px;">
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Reference" asp-action="IndexRegion">Region</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Reference" asp-action="IndexDistrict">District</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Reference" asp-action="IndexExpensesType">Expenses Type</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Report</a>
                        </li>  
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SysHotel 
        </div>
    </footer>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>